### ISSUE TITLE
Bring over the relevant pages for "Managing Large Clusters" to xcat-doc

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-doc#5]
Issue tracking moving the content under "Managing Large Cluster" from xCAT documentation over to xcat-docs. 
![image](https://cloud.githubusercontent.com/assets/10049070/8881430/bfece2a4-320d-11e5-9def-ef18615e2557.png)

The content will go under the following side bar: 
Admin Guide -> Managing Large Clusters 

AIX related content will be removed and content will be cleaned up and simplified. 
Examples should be brief and point to database documentation rather than duplicate into xCAT documentation

**Comment by whowutwut** [comment]
@lindamellor   Linda, install the unixODBC* packages in the MySQL install documentation... is that related to supporting the rolling updates w/LoadLeveler? Or is that needed in a typical MySQL install?  It was also in the pkglist for MariaDB but maybe that was just copy/paste of the pkg lists...

**Comment by whowutwut** [comment]
Should the DB2 documentation be ported over to the new docs? Do we see a mass use of DB2 on Linux plaforms?

**Comment by ligc** [comment]
DB2 is only supported for Power 775 users, I do not think we need to port the DB2 pages to github.
