### ISSUE TITLE
Create the local build dir outside of the source tree

### ISSUE THREAD

**Issue by daniceexi** [xcat2/xcat-doc#6]
For our xcat-doc, if I want to test my change locally, I just get to docs/ dir and run 'make html', then the acoording html files will be generated in ./build.  And then I use my apache server to dispaly the changes.

Everything is great except that I don't like the ./build dir is created in my git repository. I want it to be created outside of my local git repo. So I want to make following change to make sepcify the path of build.

# git diff --cached
diff --git a/docs/Makefile b/docs/Makefile
index c03d223..0db6165 100644
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -5,7 +5,7 @@
 SPHINXOPTS    =
 SPHINXBUILD   = sphinx-build
 PAPER         =
-BUILDDIR      = build
+BUILDDIR      = ../../xcatdoc_build

**Comment by whowutwut** [comment]
HI Xiao Peng, the build directory is ignored by git, part of .gitignore so there's no issues about checking in generated files.  This allows for the directory to be self contained as part of the project.   

The problem with what you suggested is that if there are multiple projects cloned, they would all overwrite the same xcatdoc_build directory generated outside the repo.   

I don't think we should make this change.

**Comment by daniceexi** [comment]
OK, agree.
